-- ============================================================================
-- COMPLETE ENUM MIGRATION SCRIPT FOR AQUAPURITE ERP
-- Database: Supabase PostgreSQL
-- Generated: 2026-01-10
-- ============================================================================
-- Run this in Supabase SQL Editor to add all missing enum values
-- ============================================================================

-- ============================================================================
-- SALES CHANNEL ENUMS (Most likely to be missing)
-- ============================================================================

-- ChannelType Enum - CRITICAL: These simplified values are likely missing
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'D2C';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'MARKETPLACE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'B2B';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'OFFLINE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'DEALER';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'D2C_WEBSITE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'D2C_APP';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'AMAZON';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'FLIPKART';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'MYNTRA';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'TATACLIQ';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'JIOMART';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'MEESHO';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'NYKAA';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'AJIO';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'RETAIL_STORE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'FRANCHISE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'DEALER_PORTAL';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'DISTRIBUTOR';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'MODERN_TRADE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'CORPORATE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'B2B_PORTAL';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'GOVERNMENT';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'EXPORT';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'QUICK_COMMERCE';
ALTER TYPE channeltype ADD VALUE IF NOT EXISTS 'OTHER';

-- ChannelStatus Enum
ALTER TYPE channelstatus ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE channelstatus ADD VALUE IF NOT EXISTS 'INACTIVE';
ALTER TYPE channelstatus ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE channelstatus ADD VALUE IF NOT EXISTS 'PENDING_SETUP';

-- ============================================================================
-- ORDER MANAGEMENT ENUMS
-- ============================================================================

-- OrderStatus Enum
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'ALLOCATED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PICKLIST_CREATED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PICKING';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PICKED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PACKING';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PACKED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'MANIFESTED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'READY_TO_SHIP';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'SHIPPED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'IN_TRANSIT';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PARTIALLY_DELIVERED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'RTO_INITIATED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'RTO_IN_TRANSIT';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'RTO_DELIVERED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'RETURNED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'ON_HOLD';

-- PaymentStatus Enum
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'AUTHORIZED';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'CAPTURED';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'PARTIALLY_PAID';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE paymentstatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- PaymentMethod Enum
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'CASH';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'CARD';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'UPI';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'NET_BANKING';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'WALLET';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'EMI';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'COD';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'CREDIT';
ALTER TYPE paymentmethod ADD VALUE IF NOT EXISTS 'CHEQUE';

-- OrderSource Enum
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'WEBSITE';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'MOBILE_APP';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'STORE';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'DEALER';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'AMAZON';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'FLIPKART';
ALTER TYPE ordersource ADD VALUE IF NOT EXISTS 'OTHER';

-- ============================================================================
-- INVENTORY MANAGEMENT ENUMS
-- ============================================================================

-- StockItemStatus Enum
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'available';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'reserved';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'allocated';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'picked';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'packed';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'in_transit';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'shipped';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'damaged';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'defective';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'sold';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'returned';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'quarantine';
ALTER TYPE stockitemstatus ADD VALUE IF NOT EXISTS 'scrapped';

-- StockMovementType Enum
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'receipt';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'issue';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'transfer_in';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'transfer_out';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'return_in';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'return_out';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'adjustment_plus';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'adjustment_minus';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'damage';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'scrap';
ALTER TYPE stockmovementtype ADD VALUE IF NOT EXISTS 'cycle_count';

-- ============================================================================
-- PURCHASE & PROCUREMENT ENUMS
-- ============================================================================

-- RequisitionStatus Enum
ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'CONVERTED';
ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- POStatus Enum
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'SENT_TO_VENDOR';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'ACKNOWLEDGED';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'PARTIALLY_RECEIVED';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'FULLY_RECEIVED';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE postatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- GRNStatus Enum
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'PENDING_QC';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'QC_PASSED';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'QC_FAILED';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'PARTIALLY_ACCEPTED';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'PUT_AWAY_PENDING';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'PUT_AWAY_COMPLETE';
ALTER TYPE grnstatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- VendorInvoiceStatus Enum
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'RECEIVED';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'UNDER_VERIFICATION';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'MATCHED';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'PARTIALLY_MATCHED';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'MISMATCH';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'PAYMENT_INITIATED';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'DISPUTED';
ALTER TYPE vendorinvoicestatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- QualityCheckResult Enum
ALTER TYPE qualitycheckresult ADD VALUE IF NOT EXISTS 'PASSED';
ALTER TYPE qualitycheckresult ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE qualitycheckresult ADD VALUE IF NOT EXISTS 'CONDITIONAL';
ALTER TYPE qualitycheckresult ADD VALUE IF NOT EXISTS 'PENDING';

-- DeliveryLotStatus Enum
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'advance_pending';
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'advance_paid';
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'delivered';
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'payment_pending';
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE deliverylotstatus ADD VALUE IF NOT EXISTS 'cancelled';

-- ProformaStatus Enum
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'RECEIVED';
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'CONVERTED_TO_PO';
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE proformastatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- ============================================================================
-- VENDOR MANAGEMENT ENUMS
-- ============================================================================

-- VendorType Enum
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'MANUFACTURER';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'IMPORTER';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'DISTRIBUTOR';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'TRADER';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'SERVICE_PROVIDER';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'RAW_MATERIAL';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'SPARE_PARTS';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'CONSUMABLES';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'TRANSPORTER';
ALTER TYPE vendortype ADD VALUE IF NOT EXISTS 'CONTRACTOR';

-- VendorStatus Enum
ALTER TYPE vendorstatus ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE vendorstatus ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE vendorstatus ADD VALUE IF NOT EXISTS 'INACTIVE';
ALTER TYPE vendorstatus ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE vendorstatus ADD VALUE IF NOT EXISTS 'BLACKLISTED';

-- VendorGrade Enum
ALTER TYPE vendorgrade ADD VALUE IF NOT EXISTS 'A+';
ALTER TYPE vendorgrade ADD VALUE IF NOT EXISTS 'A';
ALTER TYPE vendorgrade ADD VALUE IF NOT EXISTS 'B';
ALTER TYPE vendorgrade ADD VALUE IF NOT EXISTS 'C';
ALTER TYPE vendorgrade ADD VALUE IF NOT EXISTS 'D';

-- PaymentTerms Enum
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'ADVANCE';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'PARTIAL_ADVANCE';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'ON_DELIVERY';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'NET_7';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'NET_15';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'NET_30';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'NET_45';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'NET_60';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'NET_90';
ALTER TYPE paymentterms ADD VALUE IF NOT EXISTS 'CUSTOM';

-- VendorTransactionType Enum
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'OPENING_BALANCE';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'PURCHASE_INVOICE';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'PAYMENT';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'ADVANCE';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'DEBIT_NOTE';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'CREDIT_NOTE';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'TDS_DEDUCTED';
ALTER TYPE vendortransactiontype ADD VALUE IF NOT EXISTS 'ADJUSTMENT';

-- ============================================================================
-- SHIPMENT & LOGISTICS ENUMS
-- ============================================================================

-- ShipmentStatus Enum
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'CREATED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'PACKED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'READY_FOR_PICKUP';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'MANIFESTED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'PICKED_UP';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'IN_TRANSIT';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'DELIVERY_FAILED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'RTO_INITIATED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'RTO_IN_TRANSIT';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'RTO_DELIVERED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE shipmentstatus ADD VALUE IF NOT EXISTS 'LOST';

-- PaymentMode Enum (for shipments)
ALTER TYPE paymentmode ADD VALUE IF NOT EXISTS 'PREPAID';
ALTER TYPE paymentmode ADD VALUE IF NOT EXISTS 'COD';

-- PackagingType Enum
ALTER TYPE packagingtype ADD VALUE IF NOT EXISTS 'BOX';
ALTER TYPE packagingtype ADD VALUE IF NOT EXISTS 'ENVELOPE';
ALTER TYPE packagingtype ADD VALUE IF NOT EXISTS 'POLY_BAG';
ALTER TYPE packagingtype ADD VALUE IF NOT EXISTS 'PALLET';
ALTER TYPE packagingtype ADD VALUE IF NOT EXISTS 'CUSTOM';

-- ============================================================================
-- BILLING & INVOICE ENUMS
-- ============================================================================

-- InvoiceType Enum
ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'TAX_INVOICE';
ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'PROFORMA';
ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'DELIVERY_CHALLAN';
ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'EXPORT';
ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'SEZ';
ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'DEEMED_EXPORT';

-- InvoiceStatus Enum
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'GENERATED';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'IRN_PENDING';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'IRN_GENERATED';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'PARTIALLY_PAID';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'OVERDUE';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE invoicestatus ADD VALUE IF NOT EXISTS 'VOID';

-- DocumentType Enum
ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'CREDIT_NOTE';
ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'DEBIT_NOTE';

-- NoteReason Enum
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'SALES_RETURN';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'POST_SALE_DISCOUNT';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'DEFICIENCY_IN_SERVICE';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'CORRECTION_IN_INVOICE';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'CHANGE_IN_POS';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'FINALIZATION_OF_PROVISIONAL';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'PRICE_INCREASE';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'ADDITIONAL_CHARGES';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'QUALITY_VARIATION';
ALTER TYPE notereason ADD VALUE IF NOT EXISTS 'OTHER';

-- EWayBillStatus Enum
ALTER TYPE ewaybillstatus ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE ewaybillstatus ADD VALUE IF NOT EXISTS 'GENERATED';
ALTER TYPE ewaybillstatus ADD VALUE IF NOT EXISTS 'EXTENDED';
ALTER TYPE ewaybillstatus ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE ewaybillstatus ADD VALUE IF NOT EXISTS 'EXPIRED';

-- ============================================================================
-- ACCOUNTING & FINANCE ENUMS
-- ============================================================================

-- AccountType Enum
ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'ASSET';
ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'LIABILITY';
ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'EQUITY';
ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'REVENUE';
ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'EXPENSE';

-- AccountSubType Enum
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'CURRENT_ASSET';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'FIXED_ASSET';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'BANK';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'CASH';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'ACCOUNTS_RECEIVABLE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'INVENTORY';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'PREPAID_EXPENSE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'CURRENT_LIABILITY';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'LONG_TERM_LIABILITY';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'ACCOUNTS_PAYABLE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'TAX_PAYABLE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'SHARE_CAPITAL';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'RETAINED_EARNINGS';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'SALES_REVENUE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'SERVICE_REVENUE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'OTHER_INCOME';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'COST_OF_GOODS';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'OPERATING_EXPENSE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'ADMINISTRATIVE_EXPENSE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'SELLING_EXPENSE';
ALTER TYPE accountsubtype ADD VALUE IF NOT EXISTS 'TAX_EXPENSE';

-- FinancialPeriodStatus Enum
ALTER TYPE financialperiodstatus ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE financialperiodstatus ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE financialperiodstatus ADD VALUE IF NOT EXISTS 'LOCKED';

-- JournalEntryStatus Enum
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'POSTED';
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'REVERSED';
ALTER TYPE journalentrystatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- ApprovalLevel Enum
ALTER TYPE approvallevel ADD VALUE IF NOT EXISTS 'LEVEL_1';
ALTER TYPE approvallevel ADD VALUE IF NOT EXISTS 'LEVEL_2';
ALTER TYPE approvallevel ADD VALUE IF NOT EXISTS 'LEVEL_3';

-- ============================================================================
-- APPROVAL ENUMS
-- ============================================================================

-- ApprovalStatus Enum
ALTER TYPE approvalstatus ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE approvalstatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE approvalstatus ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE approvalstatus ADD VALUE IF NOT EXISTS 'ESCALATED';
ALTER TYPE approvalstatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- ApprovalEntityType Enum
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'PURCHASE_ORDER';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'PURCHASE_REQUISITION';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'STOCK_TRANSFER';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'STOCK_ADJUSTMENT';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'VENDOR_ONBOARDING';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'VENDOR_DELETION';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'DEALER_ONBOARDING';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'FRANCHISEE_CONTRACT';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'CREDIT_NOTE';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'DEBIT_NOTE';
ALTER TYPE approvalentitytype ADD VALUE IF NOT EXISTS 'SALES_CHANNEL';

-- ============================================================================
-- END OF MIGRATION SCRIPT
-- ============================================================================
--
-- To verify after running, use:
-- SELECT typname, enumlabel
-- FROM pg_enum e
-- JOIN pg_type t ON e.enumtypid = t.oid
-- ORDER BY typname, enumsortorder;
-- ============================================================================
