-- Create all ENUM types first
-- Run this BEFORE the table migrations

DO $$ BEGIN
    CREATE TYPE accountsubtype AS ENUM ('CURRENT_ASSET', 'FIXED_ASSET', 'BANK', 'CASH', 'ACCOUNTS_RECEIVABLE', 'INVENTORY', 'PREPAID_EXPENSE', 'CURRENT_LIABILITY', 'LONG_TERM_LIABILITY', 'ACCOUNTS_PAYABLE', 'TAX_PAYABLE', 'SHARE_CAPITAL', 'RETAINED_EARNINGS', 'SALES_REVENUE', 'SERVICE_REVENUE', 'OTHER_INCOME', 'COST_OF_GOODS', 'OPERATING_EXPENSE', 'ADMINISTRATIVE_EXPENSE', 'SELLING_EXPENSE', 'TAX_EXPENSE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE accounttype AS ENUM ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE activitytype AS ENUM ('CALL', 'EMAIL', 'SMS', 'WHATSAPP', 'MEETING', 'DEMO', 'SITE_VISIT', 'PROPOSAL', 'NEGOTIATION', 'FOLLOW_UP', 'NOTE', 'STATUS_CHANGE', 'ASSIGNMENT', 'CONVERSION');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE addresstype AS ENUM ('HOME', 'OFFICE', 'BILLING', 'SHIPPING', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE adjustmentstatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE adjustmenttype AS ENUM ('CYCLE_COUNT', 'DAMAGE', 'THEFT', 'EXPIRY', 'QUALITY_ISSUE', 'CORRECTION', 'WRITE_OFF', 'FOUND', 'OPENING_STOCK', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE allocationtype AS ENUM ('NEAREST', 'ROUND_ROBIN', 'FIFO', 'FIXED', 'PRIORITY', 'COST_OPTIMIZED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE amcstatus AS ENUM ('DRAFT', 'PENDING_PAYMENT', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'RENEWED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE amctype AS ENUM ('STANDARD', 'COMPREHENSIVE', 'EXTENDED_WARRANTY', 'PLATINUM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE approvalentitytype AS ENUM ('PURCHASE_ORDER', 'PURCHASE_REQUISITION', 'STOCK_TRANSFER', 'STOCK_ADJUSTMENT', 'VENDOR_ONBOARDING', 'VENDOR_DELETION', 'DEALER_ONBOARDING', 'FRANCHISEE_CONTRACT', 'JOURNAL_ENTRY', 'CREDIT_NOTE', 'DEBIT_NOTE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE approvallevel AS ENUM ('LEVEL_1', 'LEVEL_2', 'LEVEL_3');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE approvalstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'ESCALATED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE audiencetype AS ENUM ('ALL_CUSTOMERS', 'SEGMENT', 'MANUAL_LIST', 'IMPORTED', 'DYNAMIC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE auditresult AS ENUM ('PASSED', 'PASSED_WITH_OBSERVATIONS', 'FAILED', 'REQUIRES_FOLLOW_UP');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE auditstatus AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'ACTION_REQUIRED', 'CLOSED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE audittype AS ENUM ('INITIAL', 'PERIODIC', 'SURPRISE', 'COMPLIANCE', 'QUALITY', 'FINANCIAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE bintype AS ENUM ('SHELF', 'RACK', 'FLOOR', 'PALLET', 'CONTAINER', 'CAGE', 'BULK');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE businesstype AS ENUM ('B2C', 'B2B');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE calculationbasis AS ENUM ('PERCENTAGE_OF_REVENUE', 'PERCENTAGE_OF_MARGIN', 'FIXED_PER_UNIT', 'FIXED_PER_ORDER', 'SLAB_BASED', 'TIERED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE callbackstatus AS ENUM ('SCHEDULED', 'COMPLETED', 'MISSED', 'RESCHEDULED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE callcategory AS ENUM ('INSTALLATION', 'REINSTALLATION', 'BREAKDOWN', 'DEMO', 'DEALER_SUPPORT', 'COMPLAINT', 'INQUIRY', 'FEEDBACK', 'AMC', 'WARRANTY', 'SPARE_PARTS', 'BILLING', 'GENERAL', 'SALES', 'FOLLOW_UP', 'CAMPAIGN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE calloutcome AS ENUM ('RESOLVED', 'TICKET_CREATED', 'LEAD_CREATED', 'CALLBACK_SCHEDULED', 'ESCALATED', 'TRANSFERRED', 'NO_ACTION', 'CUSTOMER_NOT_AVAILABLE', 'WRONG_NUMBER', 'NOT_INTERESTED', 'INFORMATION_PROVIDED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE callpriority AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE callstatus AS ENUM ('IN_PROGRESS', 'COMPLETED', 'DROPPED', 'TRANSFERRED', 'VOICEMAIL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE calltype AS ENUM ('INBOUND', 'OUTBOUND');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE campaigncategory AS ENUM ('PROMOTIONAL', 'TRANSACTIONAL', 'INFORMATIONAL', 'REMINDER', 'FEEDBACK', 'WELCOME', 'REACTIVATION', 'LOYALTY', 'SEASONAL', 'PRODUCT_LAUNCH', 'SERVICE_UPDATE', 'AMC_RENEWAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE campaignstatus AS ENUM ('DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE campaigntype AS ENUM ('EMAIL', 'SMS', 'WHATSAPP', 'PUSH_NOTIFICATION', 'IN_APP', 'VOICE', 'MULTI_CHANNEL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE channelcode AS ENUM ('D2C', 'AMAZON', 'FLIPKART', 'MYNTRA', 'MEESHO', 'TATACLIQ', 'DEALER', 'STORE', 'ALL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE channelstatus AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_SETUP');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE channeltype AS ENUM ('D2C_WEBSITE', 'D2C_APP', 'MARKETPLACE_AMAZON', 'MARKETPLACE_FLIPKART', 'MARKETPLACE_MYNTRA', 'MARKETPLACE_TATACLIQ', 'MARKETPLACE_JIOMART', 'MARKETPLACE_MEESHO', 'MARKETPLACE_OTHER', 'RETAIL_STORE', 'FRANCHISE', 'DEALER', 'DISTRIBUTOR', 'MODERN_TRADE', 'CORPORATE', 'GOVERNMENT', 'EXPORT', 'QUICK_COMMERCE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE commissionbeneficiary AS ENUM ('SALES_EXECUTIVE', 'AREA_MANAGER', 'REGIONAL_MANAGER', 'ZONAL_HEAD', 'DEALER', 'DISTRIBUTOR', 'RETAILER', 'FRANCHISE', 'AFFILIATE', 'INFLUENCER', 'REFERRER', 'SERVICE_PARTNER', 'INSTALLATION_TEAM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE commissionstatus AS ENUM ('PENDING', 'ELIGIBLE', 'APPROVED', 'PROCESSING', 'PAID', 'CANCELLED', 'ON_HOLD', 'CLAWBACK');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE commissiontype AS ENUM ('SALES_REP', 'AREA_MANAGER', 'REGIONAL_MANAGER', 'DEALER', 'DISTRIBUTOR', 'AFFILIATE', 'INFLUENCER', 'SERVICE_ENGINEER', 'REFERRAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE companytype AS ENUM ('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'LLP', 'PARTNERSHIP', 'PROPRIETORSHIP', 'OPC', 'TRUST', 'SOCIETY', 'HUF', 'GOVERNMENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE contractstatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'EXPIRED', 'RENEWED', 'TERMINATED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE creditstatus AS ENUM ('ACTIVE', 'ON_HOLD', 'BLOCKED', 'CLOSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE customersentiment AS ENUM ('VERY_POSITIVE', 'POSITIVE', 'NEUTRAL', 'NEGATIVE', 'VERY_NEGATIVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE customersource AS ENUM ('WEBSITE', 'WALK_IN', 'REFERRAL', 'DEALER', 'CAMPAIGN', 'SOCIAL_MEDIA', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE customertype AS ENUM ('INDIVIDUAL', 'BUSINESS', 'DEALER', 'DISTRIBUTOR');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE dealerstatus AS ENUM ('PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'BLACKLISTED', 'TERMINATED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE dealertier AS ENUM ('PLATINUM', 'GOLD', 'SILVER', 'BRONZE', 'STANDARD');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE dealertype AS ENUM ('DISTRIBUTOR', 'DEALER', 'SUB_DEALER', 'RETAILER', 'FRANCHISE', 'MODERN_TRADE', 'INSTITUTIONAL', 'GOVERNMENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE deliverylotstatus AS ENUM ('PENDING', 'ADVANCE_PENDING', 'ADVANCE_PAID', 'DELIVERED', 'PAYMENT_PENDING', 'COMPLETED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE deliverystatus AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCED', 'FAILED', 'UNSUBSCRIBED', 'COMPLAINED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE discountapplication AS ENUM ('ON_MRP', 'ON_SELLING_PRICE', 'ON_CART_TOTAL', 'ON_SHIPPING', 'POST_PURCHASE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE documenttype AS ENUM ('CREDIT_NOTE', 'DEBIT_NOTE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE escalationlevel AS ENUM ('L1', 'L2', 'L3', 'L4', 'L5', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE escalationpriority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE escalationreason AS ENUM ('SLA_BREACH', 'REPEATED_COMPLAINT', 'CUSTOMER_REQUEST', 'COMPLEX_ISSUE', 'VIP_CUSTOMER', 'HIGH_VALUE', 'LEGAL_THREAT', 'SOCIAL_MEDIA_COMPLAINT', 'REGULATORY_ISSUE', 'SAFETY_CONCERN', 'PRODUCT_DEFECT', 'NO_RESPONSE', 'UNRESOLVED', 'MANAGER_OVERRIDE', 'AUTO_ESCALATION', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE escalationsource AS ENUM ('SERVICE_REQUEST', 'COMPLAINT', 'ORDER', 'CALL', 'LEAD', 'AMC', 'WARRANTY', 'BILLING', 'DELIVERY', 'INSTALLATION', 'QUALITY', 'CUSTOMER_FEEDBACK', 'SOCIAL_MEDIA', 'MANUAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE escalationstatus AS ENUM ('NEW', 'ASSIGNED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'ESCALATED', 'PENDING_RESPONSE', 'RESOLVED', 'REOPENED', 'CLOSED', 'AUTO_CLOSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE ewaybillstatus AS ENUM ('PENDING', 'GENERATED', 'EXTENDED', 'CANCELLED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE financialperiodstatus AS ENUM ('OPEN', 'CLOSED', 'LOCKED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE franchiseestatus AS ENUM ('PROSPECT', 'APPLICATION_PENDING', 'UNDER_REVIEW', 'APPROVED', 'ONBOARDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', 'INACTIVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE franchiseetier AS ENUM ('PLATINUM', 'GOLD', 'SILVER', 'BRONZE', 'STANDARD');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE franchiseetype AS ENUM ('EXCLUSIVE', 'NON_EXCLUSIVE', 'MASTER', 'SUB_FRANCHISEE', 'DEALER', 'DISTRIBUTOR');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE grnstatus AS ENUM ('DRAFT', 'PENDING_QC', 'QC_PASSED', 'QC_FAILED', 'PARTIALLY_ACCEPTED', 'ACCEPTED', 'REJECTED', 'PUT_AWAY_PENDING', 'PUT_AWAY_COMPLETE', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE gstregistrationtype AS ENUM ('REGULAR', 'COMPOSITION', 'CASUAL', 'SEZ_UNIT', 'SEZ_DEVELOPER', 'INPUT_SERVICE_DISTRIBUTOR', 'TDS_DEDUCTOR', 'TCS_COLLECTOR', 'NON_RESIDENT', 'UNREGISTERED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE installationstatus AS ENUM ('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE invoicestatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'GENERATED', 'IRN_PENDING', 'IRN_GENERATED', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'VOID');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE invoicetype AS ENUM ('TAX_INVOICE', 'PROFORMA', 'DELIVERY_CHALLAN', 'EXPORT', 'SEZ', 'DEEMED_EXPORT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE itemtype AS ENUM ('FINISHED_GOODS', 'SPARE_PART', 'COMPONENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE journalentrystatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'POSTED', 'REVERSED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE leadinterest AS ENUM ('NEW_PURCHASE', 'REPLACEMENT', 'UPGRADE', 'AMC', 'DEMO', 'INQUIRY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE leadpriority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE leadsource AS ENUM ('WEBSITE', 'PHONE_CALL', 'WALK_IN', 'REFERRAL', 'SOCIAL_MEDIA', 'EMAIL_CAMPAIGN', 'SMS_CAMPAIGN', 'EXHIBITION', 'ADVERTISEMENT', 'PARTNER', 'DEALER', 'FRANCHISEE', 'AMAZON', 'FLIPKART', 'OTHER_MARKETPLACE', 'COLD_CALL', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE leadstatus AS ENUM ('NEW', 'CONTACTED', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', 'NURTURING', 'DISQUALIFIED', 'DUPLICATE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE leadtype AS ENUM ('INDIVIDUAL', 'BUSINESS', 'GOVERNMENT', 'INSTITUTIONAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE lostreason AS ENUM ('PRICE_TOO_HIGH', 'COMPETITOR_CHOSEN', 'BUDGET_CONSTRAINTS', 'NOT_INTERESTED', 'NO_RESPONSE', 'WRONG_TIMING', 'PRODUCT_NOT_FIT', 'LOCATION_NOT_SERVICEABLE', 'CUSTOMER_POSTPONED', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE manifeststatus AS ENUM ('DRAFT', 'PENDING', 'CONFIRMED', 'HANDED_OVER', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE notereason AS ENUM ('SALES_RETURN', 'POST_SALE_DISCOUNT', 'DEFICIENCY_IN_SERVICE', 'CORRECTION_IN_INVOICE', 'CHANGE_IN_POS', 'FINALIZATION_OF_PROVISIONAL', 'PRICE_INCREASE', 'ADDITIONAL_CHARGES', 'QUALITY_VARIATION', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE notificationchannel AS ENUM ('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP', 'PUSH');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE ordersource AS ENUM ('WEBSITE', 'MOBILE_APP', 'STORE', 'PHONE', 'DEALER', 'AMAZON', 'FLIPKART', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE orderstatus AS ENUM ('NEW', 'PENDING_PAYMENT', 'CONFIRMED', 'ALLOCATED', 'PICKLIST_CREATED', 'PICKING', 'PICKED', 'PACKING', 'PACKED', 'MANIFESTED', 'READY_TO_SHIP', 'SHIPPED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'PARTIALLY_DELIVERED', 'RTO_INITIATED', 'RTO_IN_TRANSIT', 'RTO_DELIVERED', 'RETURNED', 'CANCELLED', 'REFUNDED', 'ON_HOLD');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE packagingtype AS ENUM ('BOX', 'ENVELOPE', 'POLY_BAG', 'PALLET', 'CUSTOM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE paymentmethod AS ENUM ('CASH', 'CARD', 'UPI', 'NET_BANKING', 'WALLET', 'EMI', 'COD', 'CREDIT', 'CHEQUE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE paymentmode AS ENUM ('CASH', 'CHEQUE', 'RTGS', 'NEFT', 'UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET', 'EMI', 'CREDIT', 'ADVANCE', 'TDS_DEDUCTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE paymentstatus AS ENUM ('PENDING', 'AUTHORIZED', 'CAPTURED', 'PARTIALLY_PAID', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE paymentterms AS ENUM ('ADVANCE', 'PARTIAL_ADVANCE', 'ON_DELIVERY', 'NET_7', 'NET_15', 'NET_30', 'NET_45', 'NET_60', 'NET_90', 'CUSTOM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE payoutstatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE pickliststatus AS ENUM ('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_PICKED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE picklisttype AS ENUM ('SINGLE_ORDER', 'BATCH', 'WAVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE postatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT_TO_VENDOR', 'ACKNOWLEDGED', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CLOSED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE productitemtype AS ENUM ('FG', 'SP', 'CO', 'CN', 'AC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE productstatus AS ENUM ('DRAFT', 'ACTIVE', 'INACTIVE', 'DISCONTINUED', 'OUT_OF_STOCK');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE proformastatus AS ENUM ('RECEIVED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CONVERTED_TO_PO', 'EXPIRED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE promotionscope AS ENUM ('ALL_PRODUCTS', 'SPECIFIC_PRODUCTS', 'SPECIFIC_CATEGORIES', 'SPECIFIC_BRANDS', 'CART_LEVEL', 'SHIPPING');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE promotionstatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ACTIVE', 'PAUSED', 'EXPIRED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE promotiontype AS ENUM ('PERCENTAGE_DISCOUNT', 'FLAT_DISCOUNT', 'BOGO', 'BUNDLE', 'CASHBACK', 'FREE_GIFT', 'FREE_SHIPPING', 'FLASH_SALE', 'SEASONAL', 'FIRST_ORDER', 'LOYALTY_REWARD', 'REFERRAL_REWARD', 'EXCHANGE_OFFER', 'EMI_DISCOUNT', 'BANK_OFFER', 'TRADE_DISCOUNT', 'VOLUME_REBATE', 'EARLY_PAYMENT', 'TARGET_INCENTIVE', 'DISPLAY_INCENTIVE', 'LAUNCH_SCHEME', 'CLEARANCE', 'FOC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE qastatus AS ENUM ('PENDING', 'REVIEWED', 'DISPUTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE qualitycheckresult AS ENUM ('PASSED', 'FAILED', 'CONDITIONAL', 'PENDING');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE regiontype AS ENUM ('COUNTRY', 'ZONE', 'STATE', 'CITY', 'AREA');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE requisitionstatus AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CONVERTED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE rolelevel AS ENUM ('SUPER_ADMIN', 'DIRECTOR', 'HEAD', 'MANAGER', 'EXECUTIVE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE schemetype AS ENUM ('QUANTITY_DISCOUNT', 'SLAB_DISCOUNT', 'CASH_DISCOUNT', 'EARLY_PAYMENT', 'FESTIVE_SCHEME', 'TARGET_INCENTIVE', 'PRODUCT_COMBO', 'FOC');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE serialstatus AS ENUM ('GENERATED', 'PRINTED', 'SENT_TO_VENDOR', 'RECEIVED', 'ASSIGNED', 'SOLD', 'RETURNED', 'DAMAGED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE servicepriority AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE servicesource AS ENUM ('CALL_CENTER', 'WEBSITE', 'MOBILE_APP', 'WALK_IN', 'EMAIL', 'WHATSAPP', 'AUTO_AMC', 'REFERRAL', 'SYSTEM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE servicestatus AS ENUM ('DRAFT', 'PENDING', 'ASSIGNED', 'SCHEDULED', 'EN_ROUTE', 'IN_PROGRESS', 'PARTS_REQUIRED', 'ON_HOLD', 'COMPLETED', 'CLOSED', 'CANCELLED', 'REOPENED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE servicetype AS ENUM ('INSTALLATION', 'WARRANTY_REPAIR', 'PAID_REPAIR', 'AMC_SERVICE', 'DEMO', 'PREVENTIVE_MAINTENANCE', 'COMPLAINT', 'FILTER_CHANGE', 'INSPECTION', 'UNINSTALLATION');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE shipmentstatus AS ENUM ('CREATED', 'PACKED', 'READY_FOR_PICKUP', 'MANIFESTED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELIVERY_FAILED', 'RTO_INITIATED', 'RTO_IN_TRANSIT', 'RTO_DELIVERED', 'CANCELLED', 'LOST');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE skilllevel AS ENUM ('TRAINEE', 'JUNIOR', 'SENIOR', 'EXPERT', 'MASTER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE stockitemstatus AS ENUM ('AVAILABLE', 'RESERVED', 'ALLOCATED', 'PICKED', 'PACKED', 'IN_TRANSIT', 'SHIPPED', 'DAMAGED', 'DEFECTIVE', 'SOLD', 'RETURNED', 'QUARANTINE', 'SCRAPPED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE stockmovementtype AS ENUM ('RECEIPT', 'ISSUE', 'TRANSFER_IN', 'TRANSFER_OUT', 'RETURN_IN', 'RETURN_OUT', 'ADJUSTMENT_PLUS', 'ADJUSTMENT_MINUS', 'DAMAGE', 'SCRAP', 'CYCLE_COUNT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE supportticketcategory AS ENUM ('TECHNICAL', 'BILLING', 'INVENTORY', 'MARKETING', 'OPERATIONS', 'COMPLIANCE', 'OTHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE supportticketpriority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE supportticketstatus AS ENUM ('OPEN', 'IN_PROGRESS', 'WAITING_ON_FRANCHISEE', 'ESCALATED', 'RESOLVED', 'CLOSED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE technicianstatus AS ENUM ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TRAINING', 'RESIGNED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE techniciantype AS ENUM ('INTERNAL', 'EXTERNAL', 'FREELANCE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE territorystatus AS ENUM ('PROPOSED', 'ACTIVE', 'DISPUTED', 'REVOKED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE trainingstatus AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE trainingtype AS ENUM ('ONBOARDING', 'PRODUCT', 'SALES', 'SERVICE', 'COMPLIANCE', 'CERTIFICATION', 'REFRESHER');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transactiontype AS ENUM ('INVOICE', 'PAYMENT', 'CREDIT_NOTE', 'DEBIT_NOTE', 'OPENING_BALANCE', 'ADJUSTMENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transferstatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'IN_TRANSIT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transfertype AS ENUM ('STOCK_TRANSFER', 'REPLENISHMENT', 'RETURN_TO_MAIN', 'INTER_REGION', 'DEALER_SUPPLY');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE transportertype AS ENUM ('COURIER', 'SELF_SHIP', 'MARKETPLACE', 'LOCAL', 'FRANCHISE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE vendorgrade AS ENUM ('A_PLUS', 'A', 'B', 'C', 'D');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE vendorinvoicestatus AS ENUM ('RECEIVED', 'UNDER_VERIFICATION', 'MATCHED', 'PARTIALLY_MATCHED', 'MISMATCH', 'APPROVED', 'PAYMENT_INITIATED', 'PAID', 'DISPUTED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE vendorstatus AS ENUM ('PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'BLACKLISTED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE vendortransactiontype AS ENUM ('OPENING_BALANCE', 'PURCHASE_INVOICE', 'PAYMENT', 'ADVANCE', 'DEBIT_NOTE', 'CREDIT_NOTE', 'TDS_DEDUCTED', 'ADJUSTMENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE vendortype AS ENUM ('MANUFACTURER', 'IMPORTER', 'DISTRIBUTOR', 'TRADER', 'SERVICE_PROVIDER', 'RAW_MATERIAL', 'SPARE_PARTS', 'CONSUMABLES', 'TRANSPORTER', 'CONTRACTOR');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE warehousetype AS ENUM ('MAIN', 'REGIONAL', 'SERVICE_CENTER', 'DEALER', 'VIRTUAL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zonetype AS ENUM ('RECEIVING', 'STORAGE', 'PICKING', 'PACKING', 'SHIPPING', 'RETURNS', 'QUARANTINE', 'COLD_STORAGE', 'HAZMAT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

