import {
  LayoutDashboard,
  Users,
  Shield,
  Package,
  ShoppingCart,
  Warehouse,
  Truck,
  DollarSign,
  FileText,
  Wrench,
  Store,
  MapPin,
  UserCircle,
  Megaphone,
  Barcode,
  CheckSquare,
  History,
  Settings,
  Building2,
  FolderTree,
  Tag,
  LucideIcon,
  Layers,
  Grid3X3,
  ArrowRightLeft,
  ClipboardList,
  BarChart3,
  TrendingUp,
  Scale,
  Calculator,
  Receipt,
  FileCheck,
  Clock,
  AlertTriangle,
  Gauge,
  Network,
} from 'lucide-react';

export interface NavItem {
  title: string;
  href?: string;
  icon?: LucideIcon;
  permissions?: string[];
  children?: NavItem[];
  badge?: string;
}

export const navigation: NavItem[] = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    permissions: [],
  },
  {
    title: 'Sales Channels',
    icon: Network,
    permissions: ['channels:view'],
    children: [
      { title: 'All Channels', href: '/dashboard/channels', permissions: ['channels:view'] },
      { title: 'Channel Pricing', href: '/dashboard/channels/pricing', permissions: ['channels:view'] },
      { title: 'Channel Inventory', href: '/dashboard/channels/inventory', permissions: ['channels:view'] },
      { title: 'Marketplace Orders', href: '/dashboard/channels/orders', permissions: ['channels:view'] },
      { title: 'Channel Reports', href: '/dashboard/channels/reports', permissions: ['channels:view'] },
    ],
  },
  {
    title: 'Orders',
    icon: ShoppingCart,
    permissions: ['orders:view'],
    children: [
      { title: 'All Orders', href: '/dashboard/orders', permissions: ['orders:view'] },
      { title: 'Picklists', href: '/dashboard/orders/picklists', icon: ClipboardList, permissions: ['orders:view'] },
      { title: 'Order Allocation', href: '/dashboard/orders/allocation', permissions: ['orders:view'] },
    ],
  },
  {
    title: 'Inventory',
    icon: Warehouse,
    permissions: ['inventory:view', 'warehouses:view', 'transfers:view', 'wms:view'],
    children: [
      { title: 'Stock Summary', href: '/dashboard/inventory', permissions: ['inventory:view'] },
      { title: 'Warehouses', href: '/dashboard/inventory/warehouses', permissions: ['warehouses:view'] },
      { title: 'Transfers', href: '/dashboard/inventory/transfers', permissions: ['transfers:view'] },
    ],
  },
  {
    title: 'WMS',
    icon: Grid3X3,
    permissions: ['wms:view'],
    children: [
      { title: 'Zones', href: '/dashboard/wms/zones', icon: Layers, permissions: ['wms:view'] },
      { title: 'Bins', href: '/dashboard/wms/bins', icon: Grid3X3, permissions: ['wms:view'] },
      { title: 'Putaway Rules', href: '/dashboard/wms/putaway-rules', icon: ArrowRightLeft, permissions: ['wms:view'] },
      { title: 'Bin Enquiry', href: '/dashboard/wms/bin-enquiry', permissions: ['wms:view'] },
    ],
  },
  {
    title: 'Logistics',
    icon: Truck,
    permissions: ['shipments:view'],
    children: [
      { title: 'Shipments', href: '/dashboard/logistics/shipments', permissions: ['shipments:view'] },
      { title: 'SLA Dashboard', href: '/dashboard/logistics/sla-dashboard', icon: Gauge, permissions: ['shipments:view'] },
      { title: 'Manifests', href: '/dashboard/logistics/manifests', permissions: ['shipments:view'] },
      { title: 'Transporters', href: '/dashboard/logistics/transporters', permissions: ['shipments:view'] },
      { title: 'Rate Cards', href: '/dashboard/logistics/rate-cards', icon: Calculator, permissions: ['shipments:view'] },
      { title: 'Serviceability', href: '/dashboard/logistics/serviceability', icon: MapPin, permissions: ['shipments:view'] },
      { title: 'Allocation Rules', href: '/dashboard/logistics/allocation-rules', icon: Network, permissions: ['shipments:view'] },
    ],
  },
  {
    title: 'Procurement',
    icon: Building2,
    permissions: ['vendors:view', 'purchase:view'],
    children: [
      { title: 'Vendors', href: '/dashboard/procurement/vendors', permissions: ['vendors:view'] },
      { title: 'Requisitions', href: '/dashboard/procurement/requisitions', icon: FileText, permissions: ['purchase:view'] },
      { title: 'Vendor Proformas', href: '/dashboard/procurement/vendor-proformas', permissions: ['purchase:view'] },
      { title: 'Purchase Orders', href: '/dashboard/procurement/purchase-orders', permissions: ['purchase:view'] },
      { title: 'GRN', href: '/dashboard/procurement/grn', permissions: ['grn:view'] },
      { title: 'Vendor Invoices', href: '/dashboard/procurement/vendor-invoices', icon: Receipt, permissions: ['purchase:view'] },
      { title: '3-Way Match', href: '/dashboard/procurement/three-way-match', icon: FileCheck, permissions: ['purchase:view'] },
    ],
  },
  {
    title: 'Finance',
    icon: DollarSign,
    permissions: ['accounting:view'],
    children: [
      { title: 'Chart of Accounts', href: '/dashboard/finance/chart-of-accounts', permissions: ['accounting:view'] },
      { title: 'Financial Periods', href: '/dashboard/finance/periods', icon: Clock, permissions: ['accounting:view'] },
      { title: 'Journal Entries', href: '/dashboard/finance/journal-entries', permissions: ['accounting:view'] },
      { title: 'General Ledger', href: '/dashboard/finance/general-ledger', permissions: ['accounting:view'] },
      { title: 'Cost Centers', href: '/dashboard/finance/cost-centers', permissions: ['accounting:view'] },
    ],
  },
  {
    title: 'Reports',
    icon: BarChart3,
    permissions: ['accounting:view'],
    children: [
      { title: 'Trial Balance', href: '/dashboard/reports/trial-balance', icon: Scale, permissions: ['accounting:view'] },
      { title: 'Profit & Loss', href: '/dashboard/reports/profit-loss', icon: TrendingUp, permissions: ['accounting:view'] },
      { title: 'Balance Sheet', href: '/dashboard/reports/balance-sheet', icon: BarChart3, permissions: ['accounting:view'] },
      { title: 'Channel P&L', href: '/dashboard/reports/channel-pl', permissions: ['accounting:view'] },
      { title: 'Channel Balance Sheet', href: '/dashboard/reports/channel-balance-sheet', permissions: ['accounting:view'] },
    ],
  },
  {
    title: 'Billing',
    icon: FileText,
    permissions: ['billing:view'],
    children: [
      { title: 'Invoices', href: '/dashboard/billing/invoices', permissions: ['billing:view'] },
      { title: 'E-Way Bills', href: '/dashboard/billing/eway-bills', permissions: ['billing:view'] },
      { title: 'Credit Notes', href: '/dashboard/billing/credit-notes', permissions: ['billing:view'] },
    ],
  },
  {
    title: 'Service',
    icon: Wrench,
    permissions: ['service:view', 'technicians:view'],
    children: [
      { title: 'Service Requests', href: '/dashboard/service/requests', permissions: ['service:view'] },
      { title: 'Installations', href: '/dashboard/service/installations', permissions: ['service:view'] },
      { title: 'Warranty Claims', href: '/dashboard/service/warranty-claims', icon: AlertTriangle, permissions: ['service:view'] },
      { title: 'AMC Contracts', href: '/dashboard/service/amc', permissions: ['service:view'] },
      { title: 'Technicians', href: '/dashboard/service/technicians', permissions: ['technicians:view'] },
    ],
  },
  {
    title: 'Distribution',
    icon: Store,
    permissions: ['dealers:view'],
    children: [
      { title: 'Dealers', href: '/dashboard/distribution/dealers', permissions: ['dealers:view'] },
      { title: 'Pricing Tiers', href: '/dashboard/distribution/pricing-tiers', permissions: ['dealers:view'] },
      { title: 'Franchisees', href: '/dashboard/distribution/franchisees', permissions: ['dealers:view'] },
      { title: 'Franchisee Serviceability', href: '/dashboard/distribution/franchisee-serviceability', icon: MapPin, permissions: ['dealers:view'] },
    ],
  },
  {
    title: 'Catalog',
    icon: Package,
    permissions: ['products:view', 'categories:view', 'brands:view'],
    children: [
      { title: 'All Products', href: '/dashboard/catalog', permissions: ['products:view'] },
      { title: 'Categories', href: '/dashboard/catalog/categories', icon: FolderTree, permissions: ['categories:view'] },
      { title: 'Brands', href: '/dashboard/catalog/brands', icon: Tag, permissions: ['brands:view'] },
    ],
  },
  {
    title: 'CRM',
    icon: UserCircle,
    permissions: ['customers:view', 'leads:view'],
    children: [
      { title: 'Customers', href: '/dashboard/crm/customers', permissions: ['customers:view'] },
      { title: 'Customer 360', href: '/dashboard/crm/customer-360', permissions: ['customers:view'] },
      { title: 'Leads', href: '/dashboard/crm/leads', permissions: ['leads:view'] },
      { title: 'Call Center', href: '/dashboard/crm/call-center', permissions: ['customers:view'] },
      { title: 'Escalations', href: '/dashboard/crm/escalations', permissions: ['customers:view'] },
    ],
  },
  {
    title: 'Marketing',
    icon: Megaphone,
    permissions: ['campaigns:view'],
    children: [
      { title: 'Campaigns', href: '/dashboard/marketing/campaigns', permissions: ['campaigns:view'] },
      { title: 'Promotions', href: '/dashboard/marketing/promotions', permissions: ['campaigns:view'] },
      { title: 'Commissions', href: '/dashboard/marketing/commissions', permissions: ['campaigns:view'] },
    ],
  },
  {
    title: 'Access Control',
    icon: Shield,
    permissions: ['users:view', 'roles:view'],
    children: [
      { title: 'Users', href: '/dashboard/access-control/users', permissions: ['users:view'] },
      { title: 'Roles', href: '/dashboard/access-control/roles', permissions: ['roles:view'] },
    ],
  },
  {
    title: 'Serialization',
    href: '/dashboard/serialization',
    icon: Barcode,
    permissions: ['products:view'],
  },
  {
    title: 'Approvals',
    href: '/dashboard/approvals',
    icon: CheckSquare,
    permissions: ['approvals:view'],
    badge: 'pending',
  },
  {
    title: 'Audit Logs',
    href: '/dashboard/audit-logs',
    icon: History,
    permissions: ['audit:view'],
  },
  {
    title: 'Settings',
    href: '/dashboard/settings',
    icon: Settings,
    permissions: [],
  },
];
