import {
  LayoutDashboard,
  Users,
  Shield,
  Package,
  ShoppingCart,
  Warehouse,
  Truck,
  DollarSign,
  FileText,
  Wrench,
  Store,
  MapPin,
  UserCircle,
  Megaphone,
  Barcode,
  CheckSquare,
  History,
  Settings,
  Building2,
  FolderTree,
  Tag,
  LucideIcon,
  Layers,
  Grid3X3,
  ArrowRightLeft,
  ClipboardList,
  BarChart3,
  TrendingUp,
  Scale,
  Calculator,
  Receipt,
  FileCheck,
  Clock,
  AlertTriangle,
  Gauge,
  Network,
  Briefcase,
  Calendar,
  CreditCard,
  Bell,
  Brain,
  Lightbulb,
} from 'lucide-react';

export interface NavItem {
  title: string;
  href?: string;
  icon?: LucideIcon;
  permissions?: string[];
  children?: NavItem[];
  badge?: string;
}

export const navigation: NavItem[] = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    permissions: [],
  },
  {
    title: 'AI Insights',
    icon: Brain,
    permissions: [],
    badge: 'NEW',
    children: [
      { title: 'Overview', href: '/dashboard/insights', icon: Lightbulb, permissions: [] },
      { title: 'Reorder Suggestions', href: '/dashboard/insights/reorder', permissions: [] },
      { title: 'Churn Risk', href: '/dashboard/insights/churn-risk', permissions: [] },
      { title: 'Slow Moving Stock', href: '/dashboard/insights/slow-moving', permissions: [] },
    ],
  },
  {
    title: 'Sales Channels',
    icon: Network,
    permissions: ['CHANNELS_VIEW'],
    children: [
      { title: 'All Channels', href: '/dashboard/channels', permissions: ['CHANNELS_VIEW'] },
      { title: 'Marketplaces', href: '/dashboard/channels/marketplaces', icon: Store, permissions: ['CHANNELS_VIEW'], badge: 'NEW' },
      { title: 'Channel Pricing', href: '/dashboard/channels/pricing', permissions: ['CHANNELS_VIEW'] },
      { title: 'Channel Inventory', href: '/dashboard/channels/inventory', permissions: ['CHANNELS_VIEW'] },
      { title: 'Marketplace Orders', href: '/dashboard/channels/orders', permissions: ['CHANNELS_VIEW'] },
      { title: 'Channel Reports', href: '/dashboard/channels/reports', permissions: ['CHANNELS_VIEW'] },
    ],
  },
  {
    title: 'Orders',
    icon: ShoppingCart,
    permissions: ['ORDERS_VIEW'],
    children: [
      { title: 'All Orders', href: '/dashboard/orders', permissions: ['ORDERS_VIEW'] },
      { title: 'Picklists', href: '/dashboard/orders/picklists', icon: ClipboardList, permissions: ['ORDERS_VIEW'] },
      { title: 'Order Allocation', href: '/dashboard/orders/allocation', permissions: ['ORDERS_VIEW'] },
    ],
  },
  {
    title: 'Inventory',
    icon: Warehouse,
    permissions: ['INVENTORY_VIEW', 'WAREHOUSES_VIEW', 'TRANSFERS_VIEW', 'WMS_VIEW'],
    children: [
      { title: 'Stock Summary', href: '/dashboard/inventory', permissions: ['INVENTORY_VIEW'] },
      { title: 'Warehouses', href: '/dashboard/inventory/warehouses', permissions: ['WAREHOUSES_VIEW'] },
      { title: 'Transfers', href: '/dashboard/inventory/transfers', permissions: ['TRANSFERS_VIEW'] },
    ],
  },
  {
    title: 'WMS',
    icon: Grid3X3,
    permissions: ['WMS_VIEW'],
    children: [
      { title: 'Zones', href: '/dashboard/wms/zones', icon: Layers, permissions: ['WMS_VIEW'] },
      { title: 'Bins', href: '/dashboard/wms/bins', icon: Grid3X3, permissions: ['WMS_VIEW'] },
      { title: 'Putaway Rules', href: '/dashboard/wms/putaway-rules', icon: ArrowRightLeft, permissions: ['WMS_VIEW'] },
      { title: 'Bin Enquiry', href: '/dashboard/wms/bin-enquiry', permissions: ['WMS_VIEW'] },
    ],
  },
  {
    title: 'Logistics',
    icon: Truck,
    permissions: ['SHIPMENTS_VIEW'],
    children: [
      { title: 'Shipments', href: '/dashboard/logistics/shipments', permissions: ['SHIPMENTS_VIEW'] },
      { title: 'SLA Dashboard', href: '/dashboard/logistics/sla-dashboard', icon: Gauge, permissions: ['SHIPMENTS_VIEW'] },
      { title: 'Manifests', href: '/dashboard/logistics/manifests', permissions: ['SHIPMENTS_VIEW'] },
      { title: 'Transporters', href: '/dashboard/logistics/transporters', permissions: ['SHIPMENTS_VIEW'] },
      { title: 'Rate Cards', href: '/dashboard/logistics/rate-cards', icon: Calculator, permissions: ['SHIPMENTS_VIEW'] },
      { title: 'Serviceability', href: '/dashboard/logistics/serviceability', icon: MapPin, permissions: ['SHIPMENTS_VIEW'] },
      { title: 'Allocation Rules', href: '/dashboard/logistics/allocation-rules', icon: Network, permissions: ['SHIPMENTS_VIEW'] },
    ],
  },
  {
    title: 'Procurement',
    icon: Building2,
    permissions: ['VENDORS_VIEW', 'PURCHASE_VIEW'],
    children: [
      { title: 'Vendors', href: '/dashboard/procurement/vendors', permissions: ['VENDORS_VIEW'] },
      { title: 'Requisitions', href: '/dashboard/procurement/requisitions', icon: FileText, permissions: ['PURCHASE_VIEW'] },
      { title: 'Vendor Proformas', href: '/dashboard/procurement/vendor-proformas', permissions: ['PURCHASE_VIEW'] },
      { title: 'Purchase Orders', href: '/dashboard/procurement/purchase-orders', permissions: ['PURCHASE_VIEW'] },
      { title: 'GRN', href: '/dashboard/procurement/grn', permissions: ['GRN_VIEW'] },
      { title: 'Vendor Invoices', href: '/dashboard/procurement/vendor-invoices', icon: Receipt, permissions: ['PURCHASE_VIEW'] },
      { title: '3-Way Match', href: '/dashboard/procurement/three-way-match', icon: FileCheck, permissions: ['PURCHASE_VIEW'] },
    ],
  },
  {
    title: 'Finance',
    icon: DollarSign,
    permissions: ['ACCOUNTING_VIEW', 'REPORTS_VIEW'],
    children: [
      { title: 'Chart of Accounts', href: '/dashboard/finance/chart-of-accounts', permissions: ['ACCOUNTING_VIEW'] },
      { title: 'Financial Periods', href: '/dashboard/finance/periods', icon: Clock, permissions: ['ACCOUNTING_VIEW'] },
      { title: 'Journal Entries', href: '/dashboard/finance/journal-entries', permissions: ['ACCOUNTING_VIEW'] },
      { title: 'Auto Journal', href: '/dashboard/finance/auto-journal', icon: Calculator, permissions: ['ACCOUNTING_VIEW'], badge: 'NEW' },
      { title: 'General Ledger', href: '/dashboard/finance/general-ledger', permissions: ['ACCOUNTING_VIEW'] },
      { title: 'Bank Reconciliation', href: '/dashboard/finance/bank-reconciliation', permissions: ['ACCOUNTING_VIEW'] },
      { title: 'TDS Management', href: '/dashboard/finance/tds', icon: Receipt, permissions: ['ACCOUNTING_VIEW'], badge: 'NEW' },
      { title: 'Cost Centers', href: '/dashboard/finance/cost-centers', permissions: ['ACCOUNTING_VIEW'] },
      { title: 'Fixed Assets', href: '/dashboard/finance/fixed-assets', icon: Building2, permissions: ['ACCOUNTING_VIEW'] },
    ],
  },
  {
    title: 'Reports',
    icon: BarChart3,
    permissions: ['REPORTS_VIEW', 'ACCOUNTING_VIEW'],
    children: [
      { title: 'Trial Balance', href: '/dashboard/reports/trial-balance', icon: Scale, permissions: ['REPORTS_VIEW'] },
      { title: 'Profit & Loss', href: '/dashboard/reports/profit-loss', icon: TrendingUp, permissions: ['REPORTS_VIEW'] },
      { title: 'Balance Sheet', href: '/dashboard/reports/balance-sheet', icon: BarChart3, permissions: ['REPORTS_VIEW'] },
      { title: 'Channel P&L', href: '/dashboard/reports/channel-pl', permissions: ['REPORTS_VIEW'] },
      { title: 'Channel Balance Sheet', href: '/dashboard/reports/channel-balance-sheet', permissions: ['REPORTS_VIEW'] },
    ],
  },
  {
    title: 'Billing',
    icon: FileText,
    permissions: ['BILLING_VIEW', 'ORDERS_VIEW'],
    children: [
      { title: 'Invoices', href: '/dashboard/billing/invoices', permissions: ['BILLING_VIEW'] },
      { title: 'E-Way Bills', href: '/dashboard/billing/eway-bills', permissions: ['BILLING_VIEW'] },
      { title: 'Credit Notes', href: '/dashboard/billing/credit-notes', permissions: ['BILLING_VIEW'] },
    ],
  },
  {
    title: 'Service',
    icon: Wrench,
    permissions: ['SERVICE_VIEW', 'TECHNICIANS_VIEW'],
    children: [
      { title: 'Service Requests', href: '/dashboard/service/requests', permissions: ['SERVICE_VIEW'] },
      { title: 'Installations', href: '/dashboard/service/installations', permissions: ['SERVICE_VIEW'] },
      { title: 'Warranty Claims', href: '/dashboard/service/warranty-claims', icon: AlertTriangle, permissions: ['SERVICE_VIEW'] },
      { title: 'AMC Contracts', href: '/dashboard/service/amc', permissions: ['SERVICE_VIEW'] },
      { title: 'Technicians', href: '/dashboard/service/technicians', permissions: ['TECHNICIANS_VIEW'] },
    ],
  },
  {
    title: 'Distribution',
    icon: Store,
    permissions: ['DEALERS_VIEW'],
    children: [
      { title: 'Dealers', href: '/dashboard/distribution/dealers', permissions: ['DEALERS_VIEW'] },
      { title: 'Pricing Tiers', href: '/dashboard/distribution/pricing-tiers', permissions: ['DEALERS_VIEW'] },
      { title: 'Franchisees', href: '/dashboard/distribution/franchisees', permissions: ['DEALERS_VIEW'] },
      { title: 'Franchisee Serviceability', href: '/dashboard/distribution/franchisee-serviceability', icon: MapPin, permissions: ['DEALERS_VIEW'] },
    ],
  },
  {
    title: 'HR',
    icon: Briefcase,
    permissions: ['HR_VIEW'],
    children: [
      { title: 'Dashboard', href: '/dashboard/hr', permissions: ['HR_VIEW'] },
      { title: 'Employees', href: '/dashboard/hr/employees', icon: Users, permissions: ['HR_VIEW'] },
      { title: 'Departments', href: '/dashboard/hr/departments', icon: Building2, permissions: ['HR_VIEW'] },
      { title: 'Attendance', href: '/dashboard/hr/attendance', icon: Calendar, permissions: ['ATTENDANCE_VIEW'] },
      { title: 'Leave Management', href: '/dashboard/hr/leaves', icon: Clock, permissions: ['LEAVE_VIEW'] },
      { title: 'Payroll', href: '/dashboard/hr/payroll', icon: CreditCard, permissions: ['PAYROLL_VIEW'] },
      { title: 'Performance', href: '/dashboard/hr/performance', icon: TrendingUp, permissions: ['HR_VIEW'] },
    ],
  },
  {
    title: 'Catalog',
    icon: Package,
    permissions: ['PRODUCTS_VIEW', 'CATEGORIES_VIEW', 'BRANDS_VIEW'],
    children: [
      { title: 'All Products', href: '/dashboard/catalog', permissions: ['PRODUCTS_VIEW'] },
      { title: 'Categories', href: '/dashboard/catalog/categories', icon: FolderTree, permissions: ['CATEGORIES_VIEW'] },
      { title: 'Brands', href: '/dashboard/catalog/brands', icon: Tag, permissions: ['BRANDS_VIEW'] },
    ],
  },
  {
    title: 'CRM',
    icon: UserCircle,
    permissions: ['CUSTOMERS_VIEW', 'LEADS_VIEW'],
    children: [
      { title: 'Customers', href: '/dashboard/crm/customers', permissions: ['CUSTOMERS_VIEW'] },
      { title: 'Customer 360', href: '/dashboard/crm/customer-360', permissions: ['CUSTOMERS_VIEW'] },
      { title: 'Leads', href: '/dashboard/crm/leads', permissions: ['LEADS_VIEW'] },
      { title: 'Call Center', href: '/dashboard/crm/call-center', permissions: ['CUSTOMERS_VIEW'] },
      { title: 'Escalations', href: '/dashboard/crm/escalations', permissions: ['CUSTOMERS_VIEW'] },
    ],
  },
  {
    title: 'Marketing',
    icon: Megaphone,
    permissions: ['CAMPAIGNS_VIEW'],
    children: [
      { title: 'Campaigns', href: '/dashboard/marketing/campaigns', permissions: ['CAMPAIGNS_VIEW'] },
      { title: 'Promotions', href: '/dashboard/marketing/promotions', permissions: ['CAMPAIGNS_VIEW'] },
      { title: 'Commissions', href: '/dashboard/marketing/commissions', permissions: ['CAMPAIGNS_VIEW'] },
    ],
  },
  {
    title: 'Access Control',
    icon: Shield,
    permissions: ['USERS_VIEW', 'ROLES_VIEW'],
    children: [
      { title: 'Users', href: '/dashboard/access-control/users', permissions: ['USERS_VIEW'] },
      { title: 'Roles', href: '/dashboard/access-control/roles', permissions: ['ROLES_VIEW'] },
    ],
  },
  {
    title: 'Serialization',
    href: '/dashboard/serialization',
    icon: Barcode,
    permissions: ['PRODUCTS_VIEW'],
  },
  {
    title: 'Approvals',
    href: '/dashboard/approvals',
    icon: CheckSquare,
    permissions: ['APPROVALS_VIEW'],
    badge: 'pending',
  },
  {
    title: 'Notifications',
    href: '/dashboard/notifications',
    icon: Bell,
    permissions: [],
  },
  {
    title: 'Audit Logs',
    href: '/dashboard/audit-logs',
    icon: History,
    permissions: ['AUDIT_VIEW'],
  },
  {
    title: 'Settings',
    href: '/dashboard/settings',
    icon: Settings,
    permissions: [],
  },
];
